spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guestuser
    password: guestuser
    publisher-confirm-type: correlated # Publisher Confirms 활성화
  application:
    name: HelloMessageQueue
server:
  port: 8080


